[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "builder"
path = "builder.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
chrono = "0.4"
regex = "1.10"
